# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SeO4N6OH1LOf8pJerwibfjOj4omIqIO7
"""

# Installing nltk and newspaper 3k libraries
#pip install nltk
#pip install newspaper3k

#Importing the above libraries
import nltk
from newspaper import Article

# Getting the url of the reqired article
url = 'https://www.bbc.com/news/world-south-asia-51638345'
article = Article(url)

# Performing NLP
article.download()
article.parse()
nltk.download('punkt')
article.nlp()

# Getting Authors
article.authors

#Get the publish date
article.publish_date

# Getting Top Image
article.top_image

# Getting Article Text
print(article.text)

# Article  Summary
print(article.summary)